spring.application.name=spring-supabase-jwt-auth

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://[supabase-id].supabase.co/auth/v1
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://[supabase-id].supabase.co/auth/v1/.well-known/jwks.json
spring.security.oauth2.resourceserver.jwt.jws-algorithms=ES256

#debug=true
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.security.oauth2=DEBUG
